### ISSUE TITLE
msdeploy fails on visualstudio.com

### ISSUE THREAD

**Issue by schmidtaa** [rschiefer/MSDeployAllTheThings#4]
2016-11-07T20:01:38.1589581Z ##[error]System.Management.Automation.RuntimeException: Could not find MSDeploy. Use Web Platform Installer to install the 'Web Deployment Tool' and re-run this command ---> System.Management.Automation.RuntimeException: Could not find MSDeploy. Use Web Platform Installer to install the 'Web Deployment Tool' and re-run this command
 
2016-11-07T20:01:38.1745644Z    --- End of inner exception stack trace ---
 
2016-11-07T20:01:38.1745644Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
 
2016-11-07T20:01:38.1745644Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
 
2016-11-07T20:01:38.1745644Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
 
2016-11-07T20:01:38.1745644Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
 
2016-11-07T20:01:38.1745644Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
 
2016-11-07T20:01:38.1745644Z    at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
 
2016-11-07T20:01:38.1745644Z    at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings settings)
 
2016-11-07T20:01:38.1745644Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
 
2016-11-07T20:01:38.1745644Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
 
2016-11-07T20:01:38.1745644Z ##[section]Finishing: MSDeploy Package Sync:

**Comment by rschiefer** [comment]
Looks like you need to install MSDeploy on your build agent.
